on:
  push:
    tags:
      - 'releases/*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Extract version from tag
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/releases/}"
          echo "VERSION_NAME=$TAG" >> $GITHUB_OUTPUT
          VERSION_CODE=$(echo $TAG | tr -d '.' | sed 's/^0*//')
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          VERSION_NAME: ${{ steps.version.outputs.VERSION_NAME }}
          VERSION_CODE: ${{ steps.version.outputs.VERSION_CODE }}

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ env.FIREBASE_APP_ID }}
          token: ${{ env.FIREBASE_TOKEN }}
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk
